In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'Data\1-Fannie_Mae_Multifamily.csv')

C:\Users\samvi\AppData\Local\Temp\ipykernel_8316\1241587058.py:1: DtypeWarning: Columns (12,26,29,34,35,36,37,38,39,40,46,49,51,53,54,55,56,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'Data\1-Fannie_Mae_Multifamily.csv')

In [3]:
pd.set_option('display.max_columns', None)
df.head(5)

,Loan Number,Acquisition Date,Note Date,Maturity Date at Acquisition,Loan Acquisition UPB,Amortization Type,Interest Type,Loan Product Type,Original UPB,Amortization Term,Original Interest Rate,Lien Position,Transaction ID,Issue Date,Loan Acquisition LTV,Underwritten DSCR,Underwritten DSCR Type,Original Term,Original I/O Term,I/O End Date,Loan Ever 60+ Days Delinquent,Loss Sharing Type,Modified Loss Sharing Percentage,Number of Properties at Acquisition,Property Acquisition Total Unit Count,Specific Property Type,Year Built,Property City,Property State,Property Zip Code,Metropolitan Statistical Area,Physical Occupancy %,Liquidation/Prepayment Code,Liquidation/Prepayment Date,Foreclosure Date,Credit Event Date,Foreclosure Value,Lifetime Net Credit Loss Amount,Sale Price,Default Amount,Credit Event Type,Reporting Period Date,Loan Active Property Count,Note Rate,Maturity Date - Current,UPB - Current,Delinquency UPB,Loan Payment Status,SDQ Indicator,Most Recent Modification Date,Modification Indicator,Defeasance Date,Prepayment Provision,Prepayment Provision End Date,Affordable Housing Type,MCIRT Deal ID,MCAS Deal ID,DUS Prepayment Outcomes,DUS Prepayment Segments,Loan Age,Green Bond Indicator,Social Bond Indicator
0,140296,2000-10-31,1985-07-16,2001-08-10,"$82,501.71",NaN,ARM,DUS,"$82,501.71",NaN,5.196,First,NaN,NaN,50.0,NaN,NaN,360,NaN,NaN,Y,NaN,NaN,1.0,4.0,Multifamily,NaN,SAN DIEGO,CA,92102,"SAN DIEGO-CHULA VISTA-CARLSBAD, CA METROPOLITA...",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-10-01,1.0,NaN,2001-08-10,"$82,501.71",NaN,Current,N,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,140296,2000-10-31,1985-07-16,2001-08-10,"$82,501.71",NaN,ARM,DUS,"$82,501.71",NaN,5.196,First,NaN,NaN,50.0,NaN,NaN,360,NaN,NaN,Y,NaN,NaN,1.0,4.0,Multifamily,NaN,SAN DIEGO,CA,92102,"SAN DIEGO-CHULA VISTA-CARLSBAD, CA METROPOLITA...",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-11-01,1.0,NaN,2001-08-10,"$82,501.71",NaN,Current,N,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,140296,2000-10-31,1985-07-16,2001-08-10,"$82,501.71",NaN,ARM,DUS,"$82,501.71",NaN,5.196,First,NaN,NaN,50.0,NaN,NaN,360,NaN,NaN,Y,NaN,NaN,1.0,4.0,Multifamily,NaN,SAN DIEGO,CA,92102,"SAN DIEGO-CHULA VISTA-CARLSBAD, CA METROPOLITA...",0.0,"Fully Paid, Prepaid",2000-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-01-01,1.0,5.61,2001-08-10,"$82,501.71",NaN,90+ Days Delinquent,Y,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,140296,2000-10-31,1985-07-16,2001-08-10,"$82,501.71",NaN,ARM,DUS,"$82,501.71",NaN,5.196,First,NaN,NaN,50.0,NaN,NaN,360,NaN,NaN,Y,NaN,NaN,1.0,4.0,Multifamily,NaN,SAN DIEGO,CA,92102,"SAN DIEGO-CHULA VISTA-CARLSBAD, CA METROPOLITA...",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-12-01,1.0,NaN,2001-08-10,"$82,501.71",NaN,Current,N,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,140297,2000-10-31,1985-07-18,2001-08-10,"$548,872.98",NaN,ARM,DUS,"$548,872.98",NaN,5.196,First,NaN,NaN,50.0,NaN,NaN,360,NaN,NaN,Y,NaN,NaN,1.0,2.0,Multifamily,NaN,SAN DIEGO,CA,92116,"SAN DIEGO-CHULA VISTA-CARLSBAD, CA METROPOLITA...",0.0,"Fully Paid, Prepaid",2000-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-01-01,1.0,5.55,2000-08-10,"$205,587.07",NaN,90+ Days Delinquent,Y,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
grouped = df.groupby('Loan Number')

# Filter to keep only groups where all values of 'Liquidation/Prepayment Code' are null
always_null = grouped.filter(lambda x: x['Liquidation/Prepayment Code'].isna().all())

# Count the number of unique loan numbers in that filtered DataFrame
num_unique_loans = always_null['Loan Number'].nunique()

print(num_unique_loans)

28124

In [11]:
df[df['Credit Event Type'] == 'REO']['Loan Number'].nunique()

611

In [4]:

df['Liquidation/Prepayment Code'].value_counts()

Liquidation/Prepayment Code
Fully Paid, Prepaid       35851
Fully Paid, Matured        3529
Fully Paid, Refinanced      671
Foreclosure                 642
Third Party Sale             84
Other Liquidation            69
Dissolution                  41
Repurchase                   28
Deed-in-Lieu                 27
Discounted Payoff            12
Substitution                  1
Name: count, dtype: int64

In [8]:
df[df['Liquidation/Prepayment Code']=='Fully Paid, Prepaid']

,Loan Number,Acquisition Date,Note Date,Maturity Date at Acquisition,Loan Acquisition UPB,Amortization Type,Interest Type,Loan Product Type,Original UPB,Amortization Term,Original Interest Rate,Lien Position,Transaction ID,Issue Date,Loan Acquisition LTV,Underwritten DSCR,Underwritten DSCR Type,Original Term,Original I/O Term,I/O End Date,Loan Ever 60+ Days Delinquent,Loss Sharing Type,Modified Loss Sharing Percentage,Number of Properties at Acquisition,Property Acquisition Total Unit Count,Specific Property Type,Year Built,Property City,Property State,Property Zip Code,Metropolitan Statistical Area,Physical Occupancy %,Liquidation/Prepayment Code,Liquidation/Prepayment Date,Foreclosure Date,Credit Event Date,Foreclosure Value,Lifetime Net Credit Loss Amount,Sale Price,Default Amount,Credit Event Type,Reporting Period Date,Loan Active Property Count,Note Rate,Maturity Date - Current,UPB - Current,Delinquency UPB,Loan Payment Status,SDQ Indicator,Most Recent Modification Date,Modification Indicator,Defeasance Date,Prepayment Provision,Prepayment Provision End Date,Affordable Housing Type,MCIRT Deal ID,MCAS Deal ID,DUS Prepayment Outcomes,DUS Prepayment Segments,Loan Age,Green Bond Indicator,Social Bond Indicator
2,140296,2000-10-31,1985-07-16,2001-08-10,"$82,501.71",NaN,ARM,DUS,"$82,501.71",NaN,5.196,First,NaN,NaN,50.0,NaN,NaN,360,NaN,NaN,Y,NaN,NaN,1.0,4.0,Multifamily,NaN,SAN DIEGO,CA,92102,"SAN DIEGO-CHULA VISTA-CARLSBAD, CA METROPOLITA...",0.0,"Fully Paid, Prepaid",2000-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-01-01,1.0,5.610,2001-08-10,"$82,501.71",NaN,90+ Days Delinquent,Y,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,140297,2000-10-31,1985-07-18,2001-08-10,"$548,872.98",NaN,ARM,DUS,"$548,872.98",NaN,5.196,First,NaN,NaN,50.0,NaN,NaN,360,NaN,NaN,Y,NaN,NaN,1.0,2.0,Multifamily,NaN,SAN DIEGO,CA,92116,"SAN DIEGO-CHULA VISTA-CARLSBAD, CA METROPOLITA...",0.0,"Fully Paid, Prepaid",2000-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-01-01,1.0,5.550,2000-08-10,"$205,587.07",NaN,90+ Days Delinquent,Y,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,"Fully Paid, Prepaid",2005-04-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005-04-01,1.0,7.649,2009-12-01,"$13,900,440.92",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN
140,1673867585,2000-01-01,1999-11-01,2009-12-01,"$7,248,775.03",Amortizing Balloon,Fixed,DUS,"$7,254,000.00",360.0,7.649,First,382113.0,2000-01-01,78.0,1.25,Lender UW DSCR,120,NaN,NaN,Y,NaN,NaN,1.0,224.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",93.0,"Fully Paid, Prepaid",2006-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-01,1.0,7.649,2009-12-01,"$6,719,583.13",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,80.0,N,NaN
528,1673893029,2000-01-01,1999-12-01,2010-01-01,"$4,396,000.00",Amortizing Balloon,Fixed,DUS,"$4,396,000.00",360.0,7.900,First,382183.0,2000-01-01,79.0,1.25,Lender UW DSCR,120,NaN,NaN,N,Standard DUS,NaN,1.0,132.0,Multifamily,1987,MILFORD,OH,45150,"CINCINNATI, OH-KY-IN METROPOLITAN STATISTICAL ...",81.0,"Fully Paid, Prepaid",2009-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-07-01,1.0,7.900,2010-01-01,"$3,887,179.39",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,Standard,115.0,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4959488,8300008129,2012-10-26,2012-10-01,2017-10-01,"$3,886,718.00",Amortizing Balloon,ARM,DUS,"$3,886,718.00",360.0,3.614,First,NaN,NaN,99.4,1.22,UW Actual DSCR,60,NaN,NaN,N,Standard DUS,NaN,1.0,150.0,Multifamily,1996,AUSTELL,GA,30106,"ATLANTA-SANDY SPRINGS-ALPHARETTA, GA METROPOLI...",75.4,"Fully Paid, Prepaid",2015-05-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-04-01,1.0,3.576,2017-10-01,"$3,682,525.40",NaN,Current,N,NaN,N,NaN,"L(12), 1%(45), O*(3)",NaN,NaN,NaN,NaN,Paid On or After Lock Out End Date,SARM,30.0,NaN,NaN
4959503,8300008130,2012-10-26,2012-10-01,2017-10-01,"$3,197,802.00",Amortizing Balloon,ARM,DUS,"$3,197,802.00",360.0,3.614,First,NaN,NaN,73.5,0.99,UW Actual DSCR,60,NaN,NaN,N,Standard DUS,NaN,1.0,130.0,Multifamily,1994,LAWRENCEVILLE,GA,30043,"ATLANTA-SANDY SPRINGS-ALPHARETTA, GA METROPOLI...",89.3,"Fully Paid, Prepaid",2013-12-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-11-01,1.0,3.565,2017-10-01,"$3,125,002.13",NaN,Current,N,NaN,N,NaN,"5%(12), 1%(45), O*(3)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4959526,8300008134,2013-05-31,2013-05-01,2020-05-01,"$6,260,000.00",Amortizing Balloon,Fixed,DUS,"$6,260,000.00",360.0,4.570,First,NaN,NaN,82.4,1.38,UW Actual DSCR,84,NaN,NaN,N,Pari Passu,NaN,1.0,144.0,Multifamily,2000,FOLEY,AL,36535,"DAPHNE-FAIRHOPE-FOLEY, AL METROPOLITAN STATIST...",90.0,"Fully Paid, Prepaid",2016-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-01,1.0,4.570,2020-05-01,"$6,004,329.93",NaN,Current,N,NaN,N,NaN,"YM(78), 1%(3), O*(3)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,32.0,NaN,NaN
4959619,8300008140,2015-12-29,2015-11-25,2022-12-01,"$4,250,000.00",Amortizing Balloon,ARM,DUS,"$4,250,000.00",360.0,2.880,First,NaN,NaN,77.4,1.75,UW Actual DSCR,84,NaN,NaN,N,Pari Passu,NaN,1.0,120.0,Multifamily,2001,HAILEY,ID,83333,Non MSA,95.0,"Fully Paid, Prepaid",2017-07-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-06-01,1.0,3.674,2022-12-01,"$4,123,776.12",NaN,Current,N,NaN,N,NaN,"L(12), 1%(69), O*(3)",NaN,LIHTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4959635,8300008141,2015-12-29,2015-11-25,2022-12-01,"$2,950,000.00",Amortizing Balloon,ARM,DUS,"$2,950,000.00",360.0,2.880,First,NaN,NaN,73.4,1.85,UW Actual DSCR,84,NaN,NaN,N,Pari Passu,NaN,1.0,72.0,Multifamily,2002,HAILEY,ID,83333,Non MSA,86.4,"Fully Paid, Prepaid",2017-07-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-06-01,1.0,3.674,2022-12-01,"$2,862,385.79",NaN,Current,N,NaN,N,NaN,"L(12), 1%(69), O*(3)",NaN,LIHTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df['Liquidation/Prepayment Code'].value_counts()

Liquidation/Prepayment Code
Fully Paid, Prepaid       35851
Fully Paid, Matured        3529
Fully Paid, Refinanced      671
Foreclosure                 642
Third Party Sale             84
Other Liquidation            69
Dissolution                  41
Repurchase                   28
Deed-in-Lieu                 27
Discounted Payoff            12
Substitution                  1
Name: count, dtype: int64

In [7]:
df['Sale Price'].value_counts(dropna=False)

Sale Price
NaN              4959728
$3,300,000.00         74
$2,700,000.00          6
$1,150,000.00          6
$2,800,000.00          5
                  ...
$4,670,000.00          1
$117,000.00            1
$1,080,000.00          1
$208,000.00            1
$180,000.00            1
Name: count, Length: 427, dtype: int64

In [ ]:
df['DUS Prepayment Segments'].value_counts(dropna=False)

DUS Prepayment Segments
Standard                         3627993
NonStandard                       403278
SARM                               65001
Fixed Rate, Declining Premium      31516
ARM 7-6                            27372
Name: count, dtype: int64

In [4]:
df.columns

Index(['Loan Number', 'Acquisition Date', 'Note Date',
       'Maturity Date at Acquisition', 'Loan Acquisition UPB',
       'Amortization Type', 'Interest Type', 'Loan Product Type',
       'Original UPB', 'Amortization Term', 'Original Interest Rate',
       'Lien Position', 'Transaction ID ', 'Issue Date',
       'Loan Acquisition LTV', 'Underwritten DSCR', 'Underwritten DSCR Type',
       'Original Term', 'Original I/O Term', 'I/O End Date',
       'Loan Ever 60+ Days Delinquent', 'Loss Sharing Type',
       'Modified Loss Sharing Percentage',
       'Number of Properties at Acquisition',
       'Property Acquisition Total Unit Count', 'Specific Property Type',
       'Year Built', 'Property City', 'Property State', 'Property Zip Code',
       'Metropolitan Statistical Area', 'Physical Occupancy %',
       'Liquidation/Prepayment Code', 'Liquidation/Prepayment Date',
       'Foreclosure Date', 'Credit Event Date', 'Foreclosure Value',
       'Lifetime Net Credit Loss Amount', 'Sale Price', 'Default Amount',
       'Credit Event Type', 'Reporting Period Date',
       'Loan Active Property Count', 'Note Rate', 'Maturity Date - Current',
       'UPB - Current', 'Delinquency UPB', 'Loan Payment Status',
       'SDQ Indicator', 'Most Recent Modification Date',
       'Modification Indicator', 'Defeasance Date', 'Prepayment Provision',
       'Prepayment Provision End Date', 'Affordable Housing Type',
       'MCIRT Deal ID', 'MCAS Deal ID', 'DUS Prepayment Outcomes',
       'DUS Prepayment Segments', 'Loan Age', 'Green Bond Indicator',
       'Social Bond Indicator'],
      dtype='object')

In [9]:
df['Foreclosure Date'].count()

np.int64(864)

In [15]:
df['Liquidation/Prepayment Code'].value_counts(dropna=False)

Liquidation/Prepayment Code
NaN                       4919426
Fully Paid, Prepaid         35851
Fully Paid, Matured          3529
Fully Paid, Refinanced        671
Foreclosure                   642
Third Party Sale               84
Other Liquidation              69
Dissolution                    41
Repurchase                     28
Deed-in-Lieu                   27
Discounted Payoff              12
Substitution                    1
Name: count, dtype: int64

In [6]:
df['Modification Indicator'].value_counts()

Modification Indicator
N    4921048
Y      39333
Name: count, dtype: int64

In [7]:
grouped = df.groupby("Loan Number")["Modification Indicator"]

# Count loans where it's "Y" at least once
at_least_once_Y = grouped.apply(lambda x: (x == "Y").any()).sum()

# Count loans where it's always "Y"
always_Y = grouped.apply(lambda x: (x == "Y").all()).sum()

print("Loans where 'Modification Indicator' is Y at least once:", at_least_once_Y)
print("Loans where 'Modification Indicator' is always Y:", always_Y)

Loans where 'Modification Indicator' is Y at least once: 552
Loans where 'Modification Indicator' is always Y: 380

In [19]:
modified_loans = df[df['Modification Indicator'] == 'Y']
modified_loans

,Loan Number,Acquisition Date,Note Date,Maturity Date at Acquisition,Loan Acquisition UPB,Amortization Type,Interest Type,Loan Product Type,Original UPB,Amortization Term,Original Interest Rate,Lien Position,Transaction ID,Issue Date,Loan Acquisition LTV,Underwritten DSCR,Underwritten DSCR Type,Original Term,Original I/O Term,I/O End Date,Loan Ever 60+ Days Delinquent,Loss Sharing Type,Modified Loss Sharing Percentage,Number of Properties at Acquisition,Property Acquisition Total Unit Count,Specific Property Type,Year Built,Property City,Property State,Property Zip Code,Metropolitan Statistical Area,Physical Occupancy %,Liquidation/Prepayment Code,Liquidation/Prepayment Date,Foreclosure Date,Credit Event Date,Foreclosure Value,Lifetime Net Credit Loss Amount,Sale Price,Default Amount,Credit Event Type,Reporting Period Date,Loan Active Property Count,Note Rate,Maturity Date - Current,UPB - Current,Delinquency UPB,Loan Payment Status,SDQ Indicator,Most Recent Modification Date,Modification Indicator,Defeasance Date,Prepayment Provision,Prepayment Provision End Date,Affordable Housing Type,MCIRT Deal ID,MCAS Deal ID,DUS Prepayment Outcomes,DUS Prepayment Segments,Loan Age,Green Bond Indicator,Social Bond Indicator
4660,1673966041,2000-01-01,1999-12-29,2010-01-01,"$3,210,000.00",Amortizing Balloon,Fixed,DUS,"$3,210,000.00",360.0,8.29,First,382227.0,2000-01-01,78.0,1.25,Lender UW DSCR,120,NaN,NaN,Y,Pari Passu,NaN,1.0,116.0,Multifamily,1986,LUBBOCK,TX,79414,"LUBBOCK, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-04-01,1.0,NaN,2012-01-01,"$3,204,610.83",NaN,Current,N,2010-04-01,Y,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,Standard,120.0,N,NaN
4661,1673966041,2000-01-01,1999-12-29,2010-01-01,"$3,210,000.00",Amortizing Balloon,Fixed,DUS,"$3,210,000.00",360.0,8.29,First,382227.0,2000-01-01,78.0,1.25,Lender UW DSCR,120,NaN,NaN,Y,Pari Passu,NaN,1.0,116.0,Multifamily,1986,LUBBOCK,TX,79414,"LUBBOCK, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004-12-01,1.0,8.29,2012-01-01,"$3,085,831.89",NaN,Current,N,2010-04-01,Y,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,Standard,120.0,N,NaN
4662,1673966041,2000-01-01,1999-12-29,2010-01-01,"$3,210,000.00",Amortizing Balloon,Fixed,DUS,"$3,210,000.00",360.0,8.29,First,382227.0,2000-01-01,78.0,1.25,Lender UW DSCR,120,NaN,NaN,Y,Pari Passu,NaN,1.0,116.0,Multifamily,1986,LUBBOCK,TX,79414,"LUBBOCK, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-12-01,1.0,8.29,2012-01-01,"$3,018,315.83",NaN,Current,N,2010-04-01,Y,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,Standard,120.0,N,NaN
4663,1673966041,2000-01-01,1999-12-29,2010-01-01,"$3,210,000.00",Amortizing Balloon,Fixed,DUS,"$3,210,000.00",360.0,8.29,First,382227.0,2000-01-01,78.0,1.25,Lender UW DSCR,120,NaN,NaN,Y,Pari Passu,NaN,1.0,116.0,Multifamily,1986,LUBBOCK,TX,79414,"LUBBOCK, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-09-01,1.0,8.29,2012-01-01,"$2,905,869.27",NaN,Current,N,2010-04-01,Y,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,Standard,120.0,N,NaN
4664,1673966041,2000-01-01,1999-12-29,2010-01-01,"$3,210,000.00",Amortizing Balloon,Fixed,DUS,"$3,210,000.00",360.0,8.29,First,382227.0,2000-01-01,78.0,1.25,Lender UW DSCR,120,NaN,NaN,Y,Pari Passu,NaN,1.0,116.0,Multifamily,1986,LUBBOCK,TX,79414,"LUBBOCK, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-01,1.0,8.29,2012-01-01,"$2,966,836.75",NaN,Current,N,2010-04-01,Y,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,Standard,120.0,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4959605,8300008135,2013-06-28,2013-05-30,2018-06-01,"$1,337,000.00",Amortizing Balloon,Fixed,DUS,"$1,337,000.00",300.0,4.01,First,NaN,NaN,66.9,1.44,UW Actual DSCR,60,NaN,NaN,N,Standard DUS,NaN,1.0,120.0,Military,1986,SIERRA VISTA,AZ,85635,"SIERRA VISTA-DOUGLAS, AZ METROPOLITAN STATISTI...",62.7,"Fully Paid, Matured",2018-08-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-07-01,1.0,4.01,2018-09-01,"$1,165,681.06",NaN,Current,N,2018-06-01,Y,NaN,"YM(36), 1%(21), O*(3)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,59.0,NaN,NaN
4959606,8300008135,2013-06-28,2013-05-30,2018-06-01,"$1,337,000.00",Amortizing Balloon,Fixed,DUS,"$1,337,000.00",300.0,4.01,First,NaN,NaN,66.9,1.44,UW Actual DSCR,60,NaN,NaN,N,Standard DUS,NaN,1.0,120.0,Military,1986,SIERRA VISTA,AZ,85635,"SIERRA VISTA-DOUGLAS, AZ METROPOLITAN STATISTI...",62.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-11-01,1.0,4.01,2018-09-01,"$1,260,033.66",NaN,Current,N,2018-06-01,Y,NaN,"YM(36), 1%(21), O*(3)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,59.0,NaN,NaN
4959607,8300008135,2013-06-28,2013-05-30,2018-06-01,"$1,337,000.00",Amortizing Balloon,Fixed,DUS,"$1,337,000.00",300.0,4.01,First,NaN,NaN,66.9,1.44,UW Actual DSCR,60,NaN,NaN,N,Standard DUS,NaN,1.0,120.0,Military,1986,SIERRA VISTA,AZ,85635,"SIERRA VISTA-DOUGLAS, AZ METROPOLITAN STATISTI...",62.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-07-01,1.0,4.01,2018-09-01,"$1,303,312.81",NaN,Current,N,2018-06-01,Y,NaN,"YM(36), 1%(21), O*(3)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,59.0,NaN,NaN
4959608,8300008135,2013-06-28,2013-05-30,2018-06-01,"$1,337,000.00",Amortizing Balloon,Fixed,DUS,"$1,337,000.00",300.0,4.01,First,NaN,NaN,66.9,1.44,UW Actual DSCR,60,NaN,NaN,N,Standard DUS,NaN,1.0,120.0,Military,1986,SIERRA VISTA,AZ,85635,"SIERRA VISTA-DOUGLAS, AZ METROPOLITAN STATISTI...",62.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-03-01,1.0,4.01,2018-09-01,"$1,281,827.99",NaN,Current,N,2018-06-01,Y,NaN,"YM(36), 1%(21), O*(3)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,59.0,NaN,NaN
4959609,8300008135,2013-06-28,2013-05-30,2018-06-01,"$1,337,000.00",Amortizing Balloon,Fixed,DUS,"$1,337,000.00",300.0,4.01,First,NaN,NaN,66.9,1.44,UW Actual DSCR,60,NaN,NaN,N,Standard DUS,NaN,1.0,120.0,Military,1986,SIERRA VISTA,AZ,85635,"SIERRA VISTA-DOUGLAS, AZ METROPOLITAN STATISTI...",62.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-07-01,1.0,4.01,2018-09-01,"$1,334,403.25",NaN,Current,N,2018-06-01,Y,NaN,"YM(36), 1%(21), O*(3)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,59.0,NaN,NaN

In [22]:
# Group by Loan Number and check modification counts
mod_counts = df.groupby('Loan Number')['Modification Indicator'].value_counts().unstack(fill_value=0)

# Keep only loans with both 'Yes' and 'No' (or NaN) in their history
mixed_mod_loans = mod_counts[(mod_counts.get('Y', 0) > 0) & (mod_counts.get('N', 0) > 0)].index

# Filter full dataset for those loans
mixed_mod_df = df[df['Loan Number'].isin(mixed_mod_loans)]

In [23]:
mixed_mod_df

,Loan Number,Acquisition Date,Note Date,Maturity Date at Acquisition,Loan Acquisition UPB,Amortization Type,Interest Type,Loan Product Type,Original UPB,Amortization Term,Original Interest Rate,Lien Position,Transaction ID,Issue Date,Loan Acquisition LTV,Underwritten DSCR,Underwritten DSCR Type,Original Term,Original I/O Term,I/O End Date,Loan Ever 60+ Days Delinquent,Loss Sharing Type,Modified Loss Sharing Percentage,Number of Properties at Acquisition,Property Acquisition Total Unit Count,Specific Property Type,Year Built,Property City,Property State,Property Zip Code,Metropolitan Statistical Area,Physical Occupancy %,Liquidation/Prepayment Code,Liquidation/Prepayment Date,Foreclosure Date,Credit Event Date,Foreclosure Value,Lifetime Net Credit Loss Amount,Sale Price,Default Amount,Credit Event Type,Reporting Period Date,Loan Active Property Count,Note Rate,Maturity Date - Current,UPB - Current,Delinquency UPB,Loan Payment Status,SDQ Indicator,Most Recent Modification Date,Modification Indicator,Defeasance Date,Prepayment Provision,Prepayment Provision End Date,Affordable Housing Type,MCIRT Deal ID,MCAS Deal ID,DUS Prepayment Outcomes,DUS Prepayment Segments,Loan Age,Green Bond Indicator,Social Bond Indicator
68819,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-05-01,1.0,8.25,2018-11-01,"$483,112.23",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
68820,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-11-01,1.0,8.25,2018-11-01,"$362,348.83",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
68821,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-01,1.0,8.25,2018-11-01,"$447,212.18",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
68822,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-02-01,1.0,8.25,2018-11-01,"$396,271.57",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
68823,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-06-01,1.0,8.25,2018-11-01,"$354,113.07",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4806444,8300003568,2008-06-05,2008-05-23,2018-06-01,"$1,600,000.00",Interest Only/Amortizing/Balloon,Fixed,Non-DUS,"$1,600,000.00",360.0,6.02,First,AF3853,2015-07-01,37.2,3.0,Lender UW DSCR,120,36.0,2011-06-01,Y,No Lender Loss Sharing,NaN,1.0,52.0,Cooperative,1938,SUNNYSIDE,NY,11104,"NEW YORK-NEWARK-JERSEY CITY, NY-NJ-PA METROPOL...",95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01,1.0,6.02,2019-06-01,"$1,421,020.06","$1,421,020.06",90+ Days Delinquent,Y,2019-01-18,Y,NaN,"YM(117), See Issuance Documents(3)","YM(02/28/2018), See Issuance Documents(06/01/2...",NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4806445,8300003568,2008-06-05,2008-05-23,2018-06-01,"$1,600,000.00",Interest Only/Amortizing/Balloon,Fixed,Non-DUS,"$1,600,000.00",360.0,6.02,First,AF3853,2015-07-01,37.2,3.0,Lender UW DSCR,120,36.0,2011-06-01,Y,No Lender Loss Sharing,NaN,1.0,52.0,Cooperative,1938,SUNNYSIDE,NY,11104,"NEW YORK-NEWARK-JERSEY CITY, NY-NJ-PA METROPOL...",95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010-09-01,1.0,6.02,2018-06-01,"$1,600,000.00",NaN,Current,N,NaN,N,NaN,"YM(117), See Issuance Documents(3)","YM(02/28/2018), See Issuance Documents(06/01/2...",NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4806446,8300003568,2008-06-05,2008-05-23,2018-06-01,"$1,600,000.00",Interest Only/Amortizing/Balloon,Fixed,Non-DUS,"$1,600,000.00",360.0,6.02,First,AF3853,2015-07-01,37.2,3.0,Lender UW DSCR,120,36.0,2011-06-01,Y,No Lender Loss Sharing,NaN,1.0,52.0,Cooperative,1938,SUNNYSIDE,NY,11104,"NEW YORK-NEWARK-JERSEY CITY, NY-NJ-PA METROPOL...",95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-07-01,1.0,6.02,2018-06-01,"$1,560,968.44",NaN,Current,N,NaN,N,NaN,"YM(117), See Issuance Documents(3)","YM(02/28/2018), See Issuance Documents(06/01/2...",NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4806447,8300003568,2008-06-05,2008-05-23,2018-06-01,"$1,600,000.00",Interest Only/Amortizing/Balloon,Fixed,Non-DUS,"$1,600,000.00",360.0,6.02,First,AF3853,2015-07-01,37.2,3.0,Lender UW DSCR,120,36.0,2011-06-01,Y,No Lender Loss Sharing,NaN,1.0,52.0,Cooperative,1938,SUNNYSIDE,NY,11104,"NEW YORK-NEWARK-JERSEY CITY, NY-NJ-PA METROPOL...",95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-08-01,1.0,6.02,2018-06-01,"$1,516,644.68",NaN,Current,N,NaN,N,NaN,"YM(117), See Issuance Documents(3)","YM(02/28/2018), See Issuance Documents(06/01/2...",NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4806448,8300003568,2008-06-05,2008-05-23,2018-06-01,"$1,600,000.00",Interest Only/Amortizing/Balloon,Fixed,Non-DUS,"$1,600,000.00",360.0,6.02,First,AF3853,2015-07-01,37.2,3.0,Lender UW DSCR,120,36.0,2011-06-01,Y,No Lender Loss Sharing,NaN,1.0,52.0,Cooperative,1938,SUNNYSIDE,NY,11104,"NEW YORK-NEWARK-JERSEY CITY, NY-NJ-PA METROPOL...",95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-01,1.0,6.02,2019-06-01,"$1,421,020.06",NaN,Current,N,2019-01-18,Y,NaN,"YM(117), See Issuance Documents(3)","YM(02/28/2018), See Issuance Documents(06/01/2...",NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [25]:
df[df['Loan Number'] == 1675405781].sort_values('Reporting Period Date') #140296

,Loan Number,Acquisition Date,Note Date,Maturity Date at Acquisition,Loan Acquisition UPB,Amortization Type,Interest Type,Loan Product Type,Original UPB,Amortization Term,Original Interest Rate,Lien Position,Transaction ID,Issue Date,Loan Acquisition LTV,Underwritten DSCR,Underwritten DSCR Type,Original Term,Original I/O Term,I/O End Date,Loan Ever 60+ Days Delinquent,Loss Sharing Type,Modified Loss Sharing Percentage,Number of Properties at Acquisition,Property Acquisition Total Unit Count,Specific Property Type,Year Built,Property City,Property State,Property Zip Code,Metropolitan Statistical Area,Physical Occupancy %,Liquidation/Prepayment Code,Liquidation/Prepayment Date,Foreclosure Date,Credit Event Date,Foreclosure Value,Lifetime Net Credit Loss Amount,Sale Price,Default Amount,Credit Event Type,Reporting Period Date,Loan Active Property Count,Note Rate,Maturity Date - Current,UPB - Current,Delinquency UPB,Loan Payment Status,SDQ Indicator,Most Recent Modification Date,Modification Indicator,Defeasance Date,Prepayment Provision,Prepayment Provision End Date,Affordable Housing Type,MCIRT Deal ID,MCAS Deal ID,DUS Prepayment Outcomes,DUS Prepayment Segments,Loan Age,Green Bond Indicator,Social Bond Indicator
69017,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-11-01,1.0,8.25,2018-11-01,"$485,000.00",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
68880,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-12-01,1.0,8.25,2018-11-01,"$484,690.74",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
68976,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-01-01,1.0,8.25,2018-11-01,"$484,379.35",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
68848,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-02-01,1.0,8.25,2018-11-01,"$484,065.82",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
69023,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-03-01,1.0,8.25,2018-11-01,"$483,750.13",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68856,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-01,1.0,8.25,2018-11-01,"$333,737.00",NaN,Current,N,NaN,N,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
68890,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01,1.0,8.25,2019-02-01,"$329,661.52",NaN,Current,N,2018-11-01,Y,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
68907,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-01,1.0,8.25,2019-02-01,"$329,661.52",NaN,Current,N,2018-11-01,Y,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
69013,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-03-01,1.0,8.25,2019-02-01,"$329,661.52",NaN,Current,N,2018-11-01,Y,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN
68872,1675405781,2000-11-01,2000-10-01,2018-11-01,"$485,000.00",Amortizing Balloon,Fixed,DUS,"$485,000.00",360.0,8.25,First,382785,2000-11-01,90.0,1.1,Lender UW DSCR,216,NaN,NaN,N,Standard DUS,NaN,1.0,30.0,Multifamily,1998,EL PASO,TX,79936,"EL PASO, TX METROPOLITAN STATISTICAL AREA",100.0,"Fully Paid, Matured",2019-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-04-01,1.0,8.25,2019-05-01,"$325,501.39",NaN,Current,N,2019-02-01,Y,NaN,"YM(180), O*(36)",NaN,NaN,NaN,NaN,Paid On or After Yield Maintenance End Date,NonStandard,216.0,N,NaN

In [5]:
df['Loan Number'].nunique()

69079

In [12]:
df['Loan Payment Status'].value_counts(dropna=False)

Loan Payment Status
Current                  4937083
90+ Days Delinquent        14687
30-59 Days Delinquent       5698
60-89 Days Delinquent       2913
Name: count, dtype: int64

In [18]:
always_current = df.groupby('Loan Number')['Loan Payment Status'].apply(lambda x: (x == 'Current').all())

count_always_current = always_current.sum()
print(count_always_current)

66413

In [17]:
num_ever_not_current = df.groupby('Loan Number')['Loan Payment Status'].apply(lambda x: (x != 'Current').any()).sum()
num_ever_not_current

np.int64(2666)

In [22]:
df[df['Liquidation/Prepayment Code'] == 'Fully Paid, Prepaid'].nunique()

Loan Number                     35851
Acquisition Date                 4584
Note Date                        5271
Maturity Date at Acquisition      492
Loan Acquisition UPB            15289
                                ...
DUS Prepayment Outcomes             6
DUS Prepayment Segments             5
Loan Age                          242
Green Bond Indicator                2
Social Bond Indicator               2
Length: 62, dtype: int64

In [23]:
df['Loan Number'].nunique()

69079

In [21]:
df['Liquidation/Prepayment Code'].value_counts()

Liquidation/Prepayment Code
Fully Paid, Prepaid       35851
Fully Paid, Matured        3529
Fully Paid, Refinanced      671
Foreclosure                 642
Third Party Sale             84
Other Liquidation            69
Dissolution                  41
Repurchase                   28
Deed-in-Lieu                 27
Discounted Payoff            12
Substitution                  1
Name: count, dtype: int64

In [5]:
conflicting = df.groupby('Loan Number').filter(lambda x: x['Maturity Date at Acquisition'].nunique() > 1)

print(conflicting)

Empty DataFrame
Columns: [Loan Number, Acquisition Date, Note Date, Maturity Date at Acquisition, Loan Acquisition UPB, Amortization Type, Interest Type, Loan Product Type, Original UPB, Amortization Term, Original Interest Rate, Lien Position, Transaction ID , Issue Date, Loan Acquisition LTV, Underwritten DSCR, Underwritten DSCR Type, Original Term, Original I/O Term, I/O End Date, Loan Ever 60+ Days Delinquent, Loss Sharing Type, Modified Loss Sharing Percentage, Number of Properties at Acquisition, Property Acquisition Total Unit Count, Specific Property Type, Year Built, Property City, Property State, Property Zip Code, Metropolitan Statistical Area, Physical Occupancy %, Liquidation/Prepayment Code, Liquidation/Prepayment Date, Foreclosure Date, Credit Event Date, Foreclosure Value, Lifetime Net Credit Loss Amount, Sale Price, Default Amount, Credit Event Type, Reporting Period Date, Loan Active Property Count, Note Rate, Maturity Date - Current, UPB - Current, Delinquency UPB, Loan Payment Status, SDQ Indicator, Most Recent Modification Date, Modification Indicator, Defeasance Date, Prepayment Provision, Prepayment Provision End Date, Affordable Housing Type, MCIRT Deal ID, MCAS Deal ID, DUS Prepayment Outcomes, DUS Prepayment Segments, Loan Age, Green Bond Indicator, Social Bond Indicator]
Index: []

In [6]:
df.columns

Index(['Loan Number', 'Acquisition Date', 'Note Date',
       'Maturity Date at Acquisition', 'Loan Acquisition UPB',
       'Amortization Type', 'Interest Type', 'Loan Product Type',
       'Original UPB', 'Amortization Term', 'Original Interest Rate',
       'Lien Position', 'Transaction ID ', 'Issue Date',
       'Loan Acquisition LTV', 'Underwritten DSCR', 'Underwritten DSCR Type',
       'Original Term', 'Original I/O Term', 'I/O End Date',
       'Loan Ever 60+ Days Delinquent', 'Loss Sharing Type',
       'Modified Loss Sharing Percentage',
       'Number of Properties at Acquisition',
       'Property Acquisition Total Unit Count', 'Specific Property Type',
       'Year Built', 'Property City', 'Property State', 'Property Zip Code',
       'Metropolitan Statistical Area', 'Physical Occupancy %',
       'Liquidation/Prepayment Code', 'Liquidation/Prepayment Date',
       'Foreclosure Date', 'Credit Event Date', 'Foreclosure Value',
       'Lifetime Net Credit Loss Amount', 'Sale Price', 'Default Amount',
       'Credit Event Type', 'Reporting Period Date',
       'Loan Active Property Count', 'Note Rate', 'Maturity Date - Current',
       'UPB - Current', 'Delinquency UPB', 'Loan Payment Status',
       'SDQ Indicator', 'Most Recent Modification Date',
       'Modification Indicator', 'Defeasance Date', 'Prepayment Provision',
       'Prepayment Provision End Date', 'Affordable Housing Type',
       'MCIRT Deal ID', 'MCAS Deal ID', 'DUS Prepayment Outcomes',
       'DUS Prepayment Segments', 'Loan Age', 'Green Bond Indicator',
       'Social Bond Indicator'],
      dtype='object')

In [14]:
df['Modification Indicator'].value_counts(dropna=False)

Modification Indicator
N    4921048
Y      39333
Name: count, dtype: int64

In [16]:
df[df['Loan Number'] == 1673867584]

,Loan Number,Acquisition Date,Note Date,Maturity Date at Acquisition,Loan Acquisition UPB,Amortization Type,Interest Type,Loan Product Type,Original UPB,Amortization Term,Original Interest Rate,Lien Position,Transaction ID,Issue Date,Loan Acquisition LTV,Underwritten DSCR,Underwritten DSCR Type,Original Term,Original I/O Term,I/O End Date,Loan Ever 60+ Days Delinquent,Loss Sharing Type,Modified Loss Sharing Percentage,Number of Properties at Acquisition,Property Acquisition Total Unit Count,Specific Property Type,Year Built,Property City,Property State,Property Zip Code,Metropolitan Statistical Area,Physical Occupancy %,Liquidation/Prepayment Code,Liquidation/Prepayment Date,Foreclosure Date,Credit Event Date,Foreclosure Value,Lifetime Net Credit Loss Amount,Sale Price,Default Amount,Credit Event Type,Reporting Period Date,Loan Active Property Count,Note Rate,Maturity Date - Current,UPB - Current,Delinquency UPB,Loan Payment Status,SDQ Indicator,Most Recent Modification Date,Modification Indicator,Defeasance Date,Prepayment Provision,Prepayment Provision End Date,Affordable Housing Type,MCIRT Deal ID,MCAS Deal ID,DUS Prepayment Outcomes,DUS Prepayment Segments,Loan Age,Green Bond Indicator,Social Bond Indicator
8,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005-03-01,1.0,7.649,2009-12-01,"$13,916,280.12",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN
9,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002-04-01,1.0,7.650,2009-12-01,"$14,411,758.26",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN
10,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002-12-01,1.0,7.649,2009-12-01,"$14,308,018.40",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN
11,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002-07-01,1.0,7.649,2009-12-01,"$14,373,472.44",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN
12,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-02-01,1.0,7.650,2009-12-01,"$14,581,085.13",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002-02-01,1.0,7.650,2009-12-01,"$14,436,879.69",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN
68,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004-07-01,1.0,7.649,2009-12-01,"$14,039,435.00",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN
69,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004-03-01,1.0,7.649,2009-12-01,"$14,098,704.28",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN
70,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-10-01,1.0,7.650,2009-12-01,"$14,626,761.43",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN
71,1673867584,2000-01-01,1999-11-01,2009-12-01,"$14,725,385.83",Amortizing Balloon,Fixed,DUS,"$14,736,000.00",360.0,7.649,First,382113.0,2000-01-01,80.0,1.25,Lender UW DSCR,120,NaN,NaN,N,NaN,NaN,1.0,408.0,Multifamily,1985,ARLINGTON,TX,76017,"DALLAS-FORT WORTH-ARLINGTON, TX METROPOLITAN S...",92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-03-01,1.0,7.649,2009-12-01,"$14,267,736.14",NaN,Current,N,NaN,N,NaN,"YM(114), O*(6)",NaN,NaN,NaN,NaN,Paid Prior to Yield Maintenance End Date,Standard,64.0,N,NaN

In [10]:
df['Underwritten DSCR'].value_counts(dropna=False, ascending=False)

Underwritten DSCR
1.25     557209
1.35     193971
1.30     156572
1.26     142367
1.20     133753
          ...
7.93         10
32.71         9
12.26         8
7.98          4
10.63         3
Name: count, Length: 1033, dtype: int64

In [13]:
df['Underwritten DSCR'].isna().value_counts()

Underwritten DSCR
False    4959561
True         820
Name: count, dtype: int64

In [ ]:
df['Loan Payment Status'].unique()

array(['Current', '90+ Days Delinquent', '30-59 Days Delinquent',
       '60-89 Days Delinquent'], dtype=object)

In [8]:
pd.reset_option('display.max_columns')

In [5]:
df.shape

(4960381, 62)

In [27]:
df.columns

Index(['Loan Number', 'Acquisition Date', 'Note Date',
       'Maturity Date at Acquisition', 'Loan Acquisition UPB',
       'Amortization Type', 'Interest Type', 'Loan Product Type',
       'Original UPB', 'Amortization Term', 'Original Interest Rate',
       'Lien Position', 'Transaction ID ', 'Issue Date',
       'Loan Acquisition LTV', 'Underwritten DSCR', 'Underwritten DSCR Type',
       'Original Term', 'Original I/O Term', 'I/O End Date',
       'Loan Ever 60+ Days Delinquent', 'Loss Sharing Type',
       'Modified Loss Sharing Percentage',
       'Number of Properties at Acquisition',
       'Property Acquisition Total Unit Count', 'Specific Property Type',
       'Year Built', 'Property City', 'Property State', 'Property Zip Code',
       'Metropolitan Statistical Area', 'Physical Occupancy %',
       'Liquidation/Prepayment Code', 'Liquidation/Prepayment Date',
       'Foreclosure Date', 'Credit Event Date', 'Foreclosure Value',
       'Lifetime Net Credit Loss Amount', 'Sale Price', 'Default Amount',
       'Credit Event Type', 'Reporting Period Date',
       'Loan Active Property Count', 'Note Rate', 'Maturity Date - Current',
       'UPB - Current', 'Delinquency UPB', 'Loan Payment Status',
       'SDQ Indicator', 'Most Recent Modification Date',
       'Modification Indicator', 'Defeasance Date', 'Prepayment Provision',
       'Prepayment Provision End Date', 'Affordable Housing Type',
       'MCIRT Deal ID', 'MCAS Deal ID', 'DUS Prepayment Outcomes',
       'DUS Prepayment Segments', 'Loan Age', 'Green Bond Indicator',
       'Social Bond Indicator'],
      dtype='object')

In [ ]:
#This will go from keys as HMDA to the values in Fannie Mae
cols = {'loan_amount': 'Original UPB', #could possibly be issue, might need to pair to aquisition UPB
        'Note Rate': 'interest_rate',
        'Loan Acquisition LTV': 'loan_to_value_ratio'
        ''
        }